version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app-blue
      - app-green
    networks:
      - spring-network
    restart: always

  app-blue:
    image: ${DOCKER_HUB_USERNAME}/demo:blue
    container_name: app-blue
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=blue
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/boardapp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=boarduser
      - SPRING_DATASOURCE_PASSWORD=boardpass
    networks:
      - spring-network
    restart: always

  app-green:
    image: ${DOCKER_HUB_USERNAME}/demo:green
    container_name: app-green
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=green
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/boardapp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=boarduser
      - SPRING_DATASOURCE_PASSWORD=boardpass
    networks:
      - spring-network
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: boardapp
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: boarduser
      MYSQL_PASSWORD: boardpass
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring-network
    restart: always

networks:
  spring-network:
    driver: bridge

volumes:
  mysql-data: 