name: Java CI/CD with Maven and Blue/Green Deployment

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: boardapp
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: boarduser
          MYSQL_PASSWORD: boardpass
        ports:
          - 3307:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dspring.profiles.active=test -DskipTests
    
    - name: Run tests
      run: mvn test -Dspring.profiles.active=test
      continue-on-error: true
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: demo-app
        path: target/demo-*.jar

  # 도커 이미지 빌드 및 푸시 작업 (실제 배포 필요 시 활성화)
  docker:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: demo-app
        path: target/
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/demo:latest

  # 배포 작업 (선택적)
  deploy:
    needs: docker
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd /home/${{ secrets.SERVER_USERNAME }}/app
          
          # 현재 운영 중인 환경 확인 (blue/green)
          CURRENT_ENV=$(grep -Po "server app-\K(blue|green)(?=:8080 weight=10;)" nginx/nginx.conf)
          
          if [ "$CURRENT_ENV" == "blue" ]; then
            TARGET_ENV="green"
          else
            TARGET_ENV="blue"
          fi
          
          echo "Current environment: $CURRENT_ENV, Target environment: $TARGET_ENV"
          
          # 배포 스크립트 실행
          bash scripts/deploy.sh ${{ secrets.DOCKER_HUB_USERNAME }} $TARGET_ENV 